### ISSUE TITLE
Remove Buttons from Sign in and Sign up Page

### ISSUE THREAD

**Issue by pranav-kale-01** [pranav-kale-01/excess-food-locator#5]
The Sign in and Sign up process is done directly using Google Authentication. The textfield and button present on the page are unnecessary and need to be removed.

Following is how the updated design should look like for Sign up and Sign in Page: 

### Sign in Page:

![image](https://github.com/pranav-kale-01/excess-food-locator/assets/70502672/a4581c59-dd42-4935-af6b-2652bf17874e)

### Sign Up Page:

![image](https://github.com/pranav-kale-01/excess-food-locator/assets/70502672/4d610aef-353a-4e34-9dab-5d7b3bbea908)

**Comment by Virtual4087** [comment]
I'd like to work on this

**Comment by Vidhanvyrs** [comment]
hey @pranav-kale-01 i would like to help in this issue can you please assign it to me under the label of hacktoberfest so that i can right away start working on it

**Comment by pranav-kale-01** [comment]
Sure! Create a PR with the changes.

**Comment by Vidhanvyrs** [comment]
Sorry @pranav-kale-01 I was unable to resolve this issue can you please unassign it to me

**Comment by choidf** [comment]
Could I contribute to this issue?

**Comment by pranav-kale-01** [comment]
@Vidhanvyrs No Worries! I am assigning no one to this issue, anyone who feels to contribute just create a PR and I'll merge it

**Comment by Aryashakya** [comment]
#6 Please review the PR.
